### PR TITLE
fix(pupetter): compensate for puppeteer@22 update

### PR DESCRIPTION
**Pull request by char0n**

### CODE REVIEW

**Comment by swaroopar** [comment]
Hi @char0n, Thank you for the fix.  Need a small help. We are using the `@v1` version of the action. But our job is still failing with the same `TypeError: page.waitForTimeout is not a function`  error. Could you please let me know if there is something else that needs to be done on our side to ensure the latest version of the GitHub action is used?

job sample - https://github.com/eclipse-xpanse/xpanse/actions/runs/7798652453/job/21268709802

**Comment by swaroopar** [comment]
@char0n ok sure. I had see  that the V1 tag was updated today but still our job is failing. Let me retry the job.

**Comment by swaroopar** [comment]
@char0n i get the same error still.
https://github.com/eclipse-xpanse/xpanse/actions/runs/7798008729/job/21265806861#step:7:1

Is there something else to be done on our side so that the latest version is really taken?

**Comment by char0n** [comment]
@swaroopar hm looks like some GitHub cache is involved here. Try:

```js
char0n/swagger-editor-validate@cb422b1e1eeb101aef1d8c908811c398fd4e785d
```

**Comment by char0n** [comment]
@swaroopar also your [job](https://github.com/eclipse-xpanse/xpanse/actions/runs/7798008729/job/21265806861#step:7:1) failed 2 hours ago. I've regenerated the tag just now (5 minutes ago).

**Comment by swaroopar** [comment]
@char0n the link I gave you is a very recent one. I started the job after you said that the Tag was regenerated.

**Comment by swaroopar** [comment]
@char0n you are right. Thanks for the hint. For some strange reason, the job did not start again even after submitting it. I just restarted it again. Wil let you know how it goes.

**Comment by swaroopar** [comment]
@char0n thank you. It works now. 🙏

**Pull request merged**
